name: frontend

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  tests:

    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: yarn
        cache-dependency-path: yarn.lock

    - name: install packages
      run: yarn
    - name: lint
      run: yarn lint
    - name: build
      run: yarn build
